name: "publish-npm"

on:
  release:
    types: [created]
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm install
        working-directory: ./
      - run: npm run build
        working-directory: ./
      - run: npm version patch
        working-directory: ./
      - run: npm publish --access public
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
## See docs at https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
